### ISSUE TITLE
add words into Hangman project

### ISSUE THREAD

**Issue by beumsk** [beumsk/Projects#1]
The hangman game would be better with more words to pick from. 
Add the words in the right array in the words object starting on line 7.
[Here is the JS file for this](https://github.com/beumsk/Projects/blob/master/hangman/script.js)

**Comment by neupanedipen** [comment]
Can I take this?

**Comment by ywalia01** [comment]
I'd like to work on this too

**Comment by beumsk** [comment]
Of course, thanks !

**Comment by neupanedipen** [comment]
Great. Started the work on it. Thank you!

**Comment by Vaibhav-Singh21** [comment]
hey man!! I'd like to work on this @beumsk

**Comment by ShadowFax1731** [comment]
Can I work in this too??

**Comment by ywalia01** [comment]
Hey, @beumsk I have added 9, 10 letter words and made a pull request could you please check it

**Comment by beumsk** [comment]
I'll first check the PR from @neupanedipen and @ywalia01 and then if help is still needed I'll give you both a sign @Vaibhav-Singh21 and @ShadowFax1731 🙌

**Comment by neupanedipen** [comment]
I have added the words of 3 to 8 lengths and made a pull request.

**Comment by 87johnboyle** [comment]
Still need more? Happy to help if you want. Feel free to assign it if needed :)

**Comment by kkkkkabir** [comment]
Hey! Can I work on this?

**Comment by Rehannah** [comment]
I'd like to be assigned please
